site_name: Pode.Web
site_author: Badgerati
repo_name: badgerati/pode.web
repo_url: https://github.com/Badgerati/Pode.Web
site_url: https://badgerati.github.io/Pode.Web/
edit_uri: edit/master/docs

theme:
  name: material
  logo: images/icon.png
  favicon: images/favicon.ico
  custom_dir: mkdocs-overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top
    - content.code.copy
    - content.action.edit
    - content.action.view
  font:
    text: Fira Sans
    code: Fira Code
  palette:
    - scheme: default
      primary: cyan
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Light Mode
    - scheme: slate
      primary: cyan
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Dark Mode

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - meta
  - attr_list

extra:
  version:
    provider: mike
    default: latest

  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/fRqeGcbF6h
    - icon: fontawesome/brands/github
      link: https://github.com/badgerati/pode
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/badgerati
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/badgerati/pode.web