#
# Module manifest for module 'Pode.Web'
#
# Generated by: Matthew Kelly (Badgerati)
#
# Generated on: 11/11/2020
#

@{
    # Script module or binary module file associated with this manifest.
    RootModule = 'Pode.Web.psm1'

    # Version number of this module.
    ModuleVersion = '0.4.0'

    # ID used to uniquely identify this module
    GUID = '5c6cae5a-8e62-48a4-c2e5-7511ffe2d439'

    # Author of this module
    Author = 'Matthew Kelly (Badgerati)'

    # Copyright statement for this module
    Copyright = 'Copyright (c) 2020-2021 Matthew Kelly (Badgerati), licensed under the MIT License.'

    # Description of the functionality provided by this module
    Description = 'Web template framework for the Pode PowerShell web server'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '5.0'

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{
        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @('powershell', 'web', 'server', 'pode', 'framework', 'templates', 'pages', 'charts', 'dashboard')

            # A URL to the license for this module.
            LicenseUri = 'https://raw.githubusercontent.com/Badgerati/Pode.Web/master/LICENSE.txt'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/Badgerati/Pode.Web'

            # A URL to an icon representing this module.
            IconUri = 'https://raw.githubusercontent.com/Badgerati/Pode.Web/master/images/icon.png'

        }
    }
}